### ISSUE TITLE
Related VTuber tool

### ISSUE THREAD

**Issue by paulvonlecter** [holodata/awesome-vtuber#5]
Hello, again.
I wanna suggest a collaboration assisting vtuber tool.
This has been verified by the RUVTuber community over the past year, and this still works.
- [Lecter's DOG - Discord Overlay Generator](https://paulvonlecter.github.io/DOG/)
- [Lecter's DOG source code](https://github.com/paulvonlecter/DOG)

**Comment by uetchy** [comment]
Looks awesome!
Added via 4421f43749efefc54c7d515a48014d213a90e3ef

**Comment by paulvonlecter** [comment]
> Looks awesome!
> Added via 4421f43749efefc54c7d515a48014d213a90e3ef

Please use github.io link
That more universal than link on my website dog.paulvonlecter.name

**Comment by uetchy** [comment]
done
